export type ProjectStatus = 'archived' | 'inProgress' | 'active' | 'complete';

export interface Project {
  id: number;
  title: string;
  slug: string;
  descriptions: string;
  imgSrc: string;
  link?: string;
  date: string;
  status: ProjectStatus;
  technologies: string[];
  client: string;
  category: string;
  tags: string[];
  teamSize: number;
  duration?: string;
  isFeatured: boolean;
  repo?: string;
}

export const projects: Project[] = [
  // {
  //   id: 11,
  //   title: "CashFlow Dashboard",
  //   slug: "cashflow",
  //   descriptions: "Privacy-first personal finance dashboard with PixiJS charts and bank integrations. Monorepo with Turborepo, AES-256-GCM encrypted local storage, web workers, WCAG 2 AA accessibility",
  //   imgSrc: "https://globalmap.github.io/project-list/projects/cashflow.png",
  //   date: "2025-09-10",
  //   status: "complete",
  //   technologies: ["React", "TypeScript", "Vite", "PixiJS", "Turborepo", "pnpm", "Web Workers"],
  //   client: "Me",
  //   category: "Dashboard",
  //   tags: ["finance", "dashboard", "privacy", "monorepo"],
  //   teamSize: 1,
  //   repo: "https://github.com/globalmap/CashFlow",
  //   isFeatured: false,
  // },
  {
    id: 13,
    title: "E-Commerce Admin Dashboard",
    slug: "e-commerce-admin-dashboard",
    descriptions: "Full-featured e-commerce admin dashboard with auth, KPI analytics, CRUD operations, and dark/light themes",
    imgSrc: "https://globalmap.github.io/project-list/projects/e-commerce-admin-dashboard.png",
    link: "https://e-commerce-admin-dashboard-swart.vercel.app",
    date: "2025-08-15",
    status: "complete",
    technologies: ["React", "TypeScript", "Next.js", "shadcn/ui", "Zustand", "TanStack Query", "Recharts"],
    client: "Freelance",
    category: "Dashboard",
    tags: ["admin", "dashboard", "eCommerce", "CRUD"],
    teamSize: 1,
    repo: "https://github.com/globalmap/e-commerce-admin-dashboard",
    isFeatured: false,
  },
  {
    id: 19,
    title: "N5Deal Marketplace",
    slug: "n5deal-marketplace-prototype",
    descriptions: "M&A marketplace prototype for licensed financial assets with 3 user roles, 18 demo assets across 16 countries, smart search, messaging, and admin panel",
    imgSrc: "https://globalmap.github.io/project-list/projects/n5deal-marketplace-prototype.png",
    link: "https://n5deal-marketplace-prototype.vercel.app",
    date: "2025-05-10",
    status: "complete",
    technologies: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Playwright"],
    client: "Freelance",
    category: "Web Application",
    tags: ["marketplace", "fintech", "M&A", "prototype"],
    teamSize: 1,
    repo: "https://github.com/globalmap/n5deal-marketplace-prototype",
    isFeatured: false,
  },
  {
    id: 14,
    title: "LeadFlow CMS",
    slug: "next-landing-cms-admin",
    descriptions: "B2B SaaS landing page with CMS admin panel, UTM tracking, lead management, HMAC-signed auth cookies",
    imgSrc: "https://globalmap.github.io/project-list/projects/next-landing-cms-admin.png",
    link: "https://next-landing-cms-admin.vercel.app",
    date: "2025-07-20",
    status: "complete",
    technologies: ["React", "TypeScript", "Next.js", "React Hook Form", "Zod", "Sharp"],
    client: "Freelance",
    category: "Web Application",
    tags: ["SaaS", "CMS", "landing", "B2B"],
    teamSize: 1,
    repo: "https://github.com/globalmap/next-landing-cms-admin",
    isFeatured: false,
  },
  {
    id: 15,
    title: "ProductSync",
    slug: "product-sync",
    descriptions: "Web interface for importing and synchronizing products between CSV/Excel files and e-commerce stores with 5-step wizard",
    imgSrc: "https://globalmap.github.io/project-list/projects/product-sync.png",
    link: "https://product-sync-six.vercel.app",
    date: "2025-06-25",
    status: "complete",
    technologies: ["React", "TypeScript", "Next.js", "shadcn/ui", "TanStack Query", "SheetJS"],
    client: "Freelance",
    category: "Web Application",
    tags: ["import", "sync", "eCommerce", "data"],
    teamSize: 1,
    repo: "https://github.com/globalmap/product-sync",
    isFeatured: false,
  },
  {
    id: 4,
    title: "Booking Service",
    slug: "booking-service",
    descriptions: "Booking Service for YourPriceBooking with multi-language support and complex scheduling logic",
    imgSrc: "https://globalmap.github.io/project-list/projects/yourpricebooking.png",
    link: "https://www.yourpricebooking.com/",
    date: "2024-03-05",
    status: "archived",
    technologies: ["React", "TypeScript", "Next.js"],
    client: "YourPriceBooking",
    category: "Booking",
    tags: ["eCommerce", "Localizations"],
    teamSize: 3,
    duration: "8 month",
    isFeatured: false,
  },
  {
    id: 7,
    title: "Crypto Portfolio Tracker",
    slug: "crypto-tracker",
    descriptions: "Real-time cryptocurrency portfolio management with market analytics and interactive charts",
    imgSrc: "https://globalmap.github.io/project-list/projects/crypto-tracker.png",
    link: "https://globalmap.github.io/crypto-tracker/",
    date: "2024-10-15",
    status: "complete",
    technologies: ["React", "TypeScript", "Next.js", "Recharts", "CoinGecko API"],
    client: "me",
    category: "Data Visualization",
    tags: ["crypto", "finance", "dashboard", "real-time"],
    teamSize: 2,
    duration: "4 weeks",
    repo: "https://github.com/globalmap/crypto-tracker",
    isFeatured: false,
  },
  {
    id: 12,
    title: "Creative Agency Portfolio",
    slug: "creative-agency-webgl-portfolio",
    descriptions: "Creative agency portfolio with WebGL 3D effects, GSAP animations, and Lenis smooth scrolling",
    imgSrc: "https://globalmap.github.io/project-list/projects/creative-agency-webgl-portfolio.png",
    link: "https://creative-agency-webgl-portfolio.vercel.app",
    date: "2025-10-05",
    status: "complete",
    technologies: ["React", "TypeScript", "Next.js", "Three.js", "React Three Fiber", "GSAP", "Lenis"],
    client: "Me",
    category: "Portfolio",
    tags: ["3D", "WebGL", "portfolio", "agency"],
    teamSize: 1,
    isFeatured: false,
  },
  {
    id: 20,
    title: "ORBIT - Solar System",
    slug: "orbit",
    descriptions: "Interactive 3D solar system with orbiting planets, info panels, speed controls, compare mode, timeline, and quiz",
    imgSrc: "https://globalmap.github.io/project-list/projects/orbit.png",
    link: "https://orbit-ten-tan-25.vercel.app",
    date: "2025-12-05",
    status: "complete",
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "Postprocessing", "Tailwind CSS"],
    client: "Me",
    category: "Interactive Visualization",
    tags: ["3D", "WebGL", "solar-system", "education", "interactive"],
    teamSize: 1,
    repo: "https://github.com/globalmap/ORBIT",
    isFeatured: false,
  },
  // {
  //   id: 17,
  //   title: "Luxury Watch Landing",
  //   slug: "luxury-watch-landing",
  //   descriptions: "Premium luxury watch landing page with 3D watch rendering, GSAP animations, and Zustand state management",
  //   imgSrc: "https://globalmap.github.io/project-list/projects/luxury-watch-landing.png",
  //   link: "https://luxury-watch-landing-six.vercel.app",
  //   date: "2025-10-25",
  //   status: "complete",
  //   technologies: ["React", "TypeScript", "Next.js", "Three.js", "React Three Fiber", "GSAP", "Zustand"],
  //   client: "Me",
  //   category: "Landing Page",
  //   tags: ["3D", "WebGL", "luxury", "landing", "watch"],
  //   teamSize: 1,
  //   isFeatured: false,
  // },
  {
    id: 24,
    title: "Virtual 3D Showroom",
    slug: "virtual-3d-showroom",
    descriptions: "Virtual 3D product showroom with immersive product visualization and GSAP animations",
    imgSrc: "https://globalmap.github.io/project-list/projects/virtual-3d-showroom.png",
    link: "https://virtual-3d-showroom.vercel.app",
    date: "2025-11-25",
    status: "complete",
    technologies: ["React", "TypeScript", "Next.js", "Three.js", "React Three Fiber", "GSAP"],
    client: "Me",
    category: "Interactive Visualization",
    tags: ["3D", "WebGL", "showroom", "products"],
    teamSize: 1,
    repo: "https://github.com/globalmap/virtual-3d-showroom",
    isFeatured: false,
  },
  {
    id: 18,
    title: "Music Release Experience",
    slug: "music-release-web-experience",
    descriptions: "Immersive music release web experience with WebGL postprocessing effects and GSAP animations",
    imgSrc: "https://globalmap.github.io/project-list/projects/music-release-web-experience.png",
    link: "https://music-release-web-experience.vercel.app",
    date: "2025-11-10",
    status: "complete",
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "Postprocessing", "GSAP"],
    client: "Me",
    category: "Interactive Visualization",
    tags: ["3D", "WebGL", "music", "immersive", "postprocessing"],
    teamSize: 1,
    isFeatured: false,
  },
  // {
  //   id: 22,
  //   title: "Real Estate 3D Experience",
  //   slug: "real-estate-3d-experience",
  //   descriptions: "3D real estate visualization experience with Three.js, GSAP animations, and Zustand state management",
  //   imgSrc: "https://globalmap.github.io/project-list/projects/real-estate-3d-experience.png",
  //   link: "https://real-estate-3d-experience.vercel.app",
  //   date: "2025-11-20",
  //   status: "complete",
  //   technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "GSAP", "Zustand"],
  //   client: "Me",
  //   category: "Interactive Visualization",
  //   tags: ["3D", "WebGL", "real-estate", "visualization"],
  //   teamSize: 1,
  //   repo: "https://github.com/globalmap/real-estate-3d-experience",
  //   isFeatured: false,
  // },
  {
    id: 16,
    title: "Interactive 3D Globe",
    slug: "interactive-3d-globe",
    descriptions: "Interactive 3D globe visualization with geographic data using D3, TopoJSON, and Three.js",
    imgSrc: "https://globalmap.github.io/project-list/projects/interactive-3d-globe.png",
    link: "https://interactive-3d-globe.vercel.app",
    date: "2025-11-01",
    status: "complete",
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "D3.js", "TopoJSON"],
    client: "Me",
    category: "Interactive Visualization",
    tags: ["3D", "WebGL", "globe", "geography", "data-viz"],
    teamSize: 1,
    repo: "https://github.com/globalmap/interactive-3d-globe",
    isFeatured: false,
  },
  {
    id: 2,
    title: "Sofa Cofigurator",
    slug: "living-spaces",
    descriptions: "Sofa Cofigurator for living spaces",
    imgSrc: "https://globalmap.github.io/project-list/projects/living-spaces.png",
    date: "2022-01-25",
    status: "complete",
    technologies: ["WebGL", "React", "Javascript", "SCSS"],
    client: "Living Spaces",
    category: "Product Configurator",
    tags: ["eCommerce", "3D", "WebGL"],
    teamSize: 4,
    duration: "6 month",
    isFeatured: false,
  },
  {
    id: 9,
    title: "3D Product Landing Page",
    slug: "3d-product-landing-page",
    descriptions: "Immersive 3D product landing page with GSAP scroll animations and Three.js rendering",
    imgSrc: "https://globalmap.github.io/project-list/projects/3d-product-landing-page.png",
    link: "https://3d-product-landing-page-omega.vercel.app",
    date: "2025-11-15",
    status: "complete",
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "GSAP", "Tailwind CSS"],
    client: "Me",
    category: "Landing Page",
    tags: ["3D", "WebGL", "landing", "GSAP"],
    teamSize: 1,
    isFeatured: false,
    repo: "https://github.com/globalmap/3d-product-landing-page",
  },
  {
    id: 8,
    title: "3D Furniture Configurator",
    slug: "3d-furniture-configurator",
    descriptions: "Interactive 3D furniture configurator with real-time customization using Three.js and React Three Fiber",
    imgSrc: "https://globalmap.github.io/project-list/projects/3d-furniture-configurator.png",
    link: "https://3d-furniture-configurator-eight.vercel.app",
    date: "2025-12-01",
    status: "complete",
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "Zustand", "Tailwind CSS"],
    client: "Me",
    category: "Product Configurator",
    tags: ["3D", "WebGL", "configurator", "furniture"],
    teamSize: 1,
    isFeatured: false,
    repo: "https://github.com/globalmap/3d-furniture-configurator",
  },
  {
    id: 23,
    title: "Sneaker Customizer",
    slug: "sneaker-customizer",
    descriptions: "3D sneaker customizer with real-time color/variant selection using Three.js and Zustand",
    imgSrc: "https://globalmap.github.io/project-list/projects/sneaker-customizer.png",
    link: "https://sneaker-customizer-drab.vercel.app",
    date: "2025-10-30",
    status: "complete",
    technologies: ["React", "TypeScript", "Three.js", "React Three Fiber", "Zustand", "Tailwind CSS"],
    client: "Me",
    category: "Product Configurator",
    tags: ["3D", "WebGL", "sneaker", "customizer", "fashion"],
    teamSize: 1,
    repo: "https://github.com/globalmap/sneaker-customizer",
    isFeatured: false,
  },
  {
    id: 21,
    title: "Personal Portfolio",
    slug: "personal-site",
    descriptions: "Personal portfolio site with blueprint theme, GSAP reveals, and interactive 3D background using raw Three.js",
    imgSrc: "https://globalmap.github.io/project-list/projects/personal-site.png",
    link: "https://globalmap.github.io/",
    date: "2025-09-01",
    status: "complete",
    technologies: ["React", "TypeScript", "Three.js", "GSAP", "Tailwind CSS"],
    client: "Me",
    category: "Portfolio",
    tags: ["portfolio", "3D", "personal", "GSAP"],
    teamSize: 1,
    repo: "https://github.com/globalmap/personal",
    isFeatured: false,
  },
  {
    id: 0,
    title: "Table Configurator",
    slug: "table-configurator",
    descriptions: "Table configurator for stone labs",
    imgSrc: "https://globalmap.github.io/project-list/projects/stone-labs.png",
    link: "https://stone-lab.nl/product/configurator",
    date: "2025-04-05",
    status: "complete",
    technologies: ["Three.js", "JavaScript", "CSS"],
    client: "Stone Labs",
    category: "Product Configurator",
    tags: ["3D", "eCommerce", "WebGL"],
    teamSize: 4,
    duration: "3 weeks",
    isFeatured: false,
  },
  // {
  //   id: 10,
  //   title: "Car Detailing",
  //   slug: "car-detailing",
  //   descriptions: "Modern car detailing service website built with Next.js and Tailwind CSS",
  //   imgSrc: "https://globalmap.github.io/project-list/projects/car-detailing.png",
  //   link: "https://car-detailing-eight-eta.vercel.app",
  //   date: "2025-10-20",
  //   status: "complete",
  //   technologies: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
  //   client: "Me",
  //   category: "Landing Page",
  //   tags: ["landing", "services", "automotive"],
  //   teamSize: 1,
  //   isFeatured: false,
  // },
  {
    id: 6,
    title: "Space Explorer Dashboard",
    slug: "space-explorer",
    descriptions: "Real-time space data visualization using NASA and SpaceX APIs",
    imgSrc: "https://globalmap.github.io/project-list/projects/space-explorer.png",
    link: "https://globalmap.github.io/space-explorer/",
    date: "2025-10-10",
    status: "complete",
    technologies: ["React", "TypeScript", "D3.js", "REST API"],
    client: "Me",
    category: "Data Visualization",
    tags: ["API", "demo", "data-viz", "astronomy"],
    teamSize: 1,
    duration: "2 days",
    repo: "https://github.com/globalmap/space-explorer",
    isFeatured: false,
  },
  {
    id: 3,
    title: "Rings Builder",
    slug: "rings-builder",
    descriptions: "Rings Builder for Anna Sheffield",
    imgSrc: "https://www.elementalsweb.com/pages/portfolio/rings.png",
    date: "2021-08-20",
    status: "complete",
    technologies: ["React", "JavaScript"],
    client: "Anna Sheffield",
    category: "Product Configurator",
    tags: ["3D", "eCommerce", "WebGL"],
    teamSize: 2,
    duration: "3 month",
    isFeatured: false,
  },
  {
    id: 5,
    title: "Markdown Editor",
    slug: "markdown-editor",
    descriptions: "Markdown Editor with live preview and syntax highlighting",
    imgSrc: "https://globalmap.github.io/project-list/projects/markdown-editor.png",
    link: "https://globalmap.github.io/markdown-editor/",
    date: "2024-07-05",
    status: "complete",
    technologies: ["React", "TypeScript"],
    client: "Me",
    category: "Demo",
    tags: ["demo", "antd", "markdown"],
    teamSize: 1,
    duration: "1 week",
    isFeatured: false,
  },
  {
    id: 1,
    title: "Gallery",
    slug: "gallery",
    descriptions: "Photo Gallery",
    imgSrc: "https://globalmap.github.io/project-list/projects/gallery.png",
    link: "https://globalmap.github.io/gallery/",
    date: "2023-05-20",
    status: "complete",
    technologies: ["React", "TypeScript", "CSS", "SCSS"],
    client: "Me",
    category: "Demo",
    tags: ["demo", "antd"],
    teamSize: 1,
    repo: "https://github.com/globalmap/gallery",
    isFeatured: false,
  },
];
